name: Extract Zip File

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unzip and push
        run: |
          # Hapus folder lama (opsional)
          rm -rf lib WAProto

          # Ekstrak semua file ZIP
          unzip -o '*.zip' -d temp

          # Pindahkan isi ke root
          mv temp/*/* . 2>/dev/null || mv temp/* .

          # Hapus ZIP dan folder temp
          rm -rf temp *.zip

          # Commit & push hasil ekstrak
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto unzip" || echo "No changes"
          git push
